---
- name: Docker_install_reut
  hosts: nodes
  become: true
  
  tasks:
    - name: "APT - install misc packages"
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common','gnupg-agent']
        update_cache: yes

    - name: APT - Add Docker GPG key
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "APT - Add Docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present
        filename: docker

    - name: "APT - install 'docker-ce'"
      apt:
        name: ['docker-ce','docker-ce-cli','containerd.io']
        state: latest
        update_cache: yes 
      notify:
        - Restart docker

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker

    # Install pip and docker SDK for python to allow the usage of community.general.docker_container module
    - name: Install pip3
      apt:
        name: python3-pip
        state: latest

    - name: Install docker SDK for python 
      pip:
        name: docker
        state: present

    - name: Flush handler (restart docker)
      meta: flush_handlers

    - name: run ngnix (docker_container)
      community.general.docker_container: 
        name: ngnix_reut
        image: nginx
        state: started
        detach: yes  
        ports:  # Publish container port 80 as host port 8080
          - "8080:80"
          
  handlers: 
    - name: Restart docker
      service:
        name: docker
        state: restarted


